# Site settings
title: AirSense UK Ltd
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  AirSense UK Ltd Homepage
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site



# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'