# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll"
gem "jekyll-paginate"

# gem "github-pages", "~> GITHUB-PAGES-VERSION", group: :jekyll_plugins

gem "webrick", "~> 1.7"